version: '3.8'
services:
  app:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file: 
      - .env
